name: quantum-ald
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  - pandas
  - pyyaml
  - pip
  - jupyter
  - black
  - pytest
  - pip:
      - pyscf
      - qiskit
      - qiskit-nature
      - qiskit-aer
      - qiskit-algorithms
      - qiskit-ibm-runtime
      - openfermion
      - openfermion-pyscf
      - pennylane
      - pennylane-qiskit
