"""Hybrid quantum-classical workflow for Atomic Layer Deposition reactions."""

from .active_space import (
    CAS_2_2,
    CAS_4_4,
    CAS_6_6,
    CAS_8_8,
    ActiveSpaceConfig,
    PreparedElectronicProblem,
    avas_selection,
    define_active_space,
    prepare_active_space_problem,
    run_active_space_casci_reference,
)
from .active_space_sweep import (
    ActiveSpaceComparisonEntry,
    ActiveSpaceSweepConfig,
    ActiveSpaceSweepResult,
    run_active_space_sweep,
)
from .ald_models import ALDProxyModel, get_ald_proxy_model, list_ald_proxy_models
from .ansatz import (
    AnsatzConfig,
    PreparedAnsatz,
    build_reference_state_circuit,
    prepare_ansatz,
)
from .classical_methods import (
    get_density_matrix,
    get_fock_matrix,
    get_orbital_energies,
    run_casscf,
    run_casci,
    run_dft,
    run_hartree_fock,
    run_fci,
)
from .error_mitigation import CDR, ZNE
from .experiment import (
    AtomSpec,
    ExperimentConfig,
    ExperimentConfigurationError,
    ExperimentResult,
    MoleculeSpec,
    run_experiment,
)
from .generic_vqe import (
    GenericVQESolver,
    StatevectorEstimatorEvaluator,
    VQEConvergencePoint,
    VQEResult,
    VQERunResult,
    VQESolverConfig,
    run_vqe,
)
from .electronic_structure import (
    ElectronicHamiltonianData,
    SpinOrbitalHamiltonianData,
    build_spin_orbital_integrals,
    expand_to_spin_orbitals,
    extract_electronic_hamiltonian_data,
    spatial_index,
    spin_index,
    spin_orbital_index,
    spin_orbital_label,
)
from .hamiltonian_mapping import (
    build_many_body_hamiltonian,
    build_many_body_hamiltonian_from_data,
    build_many_body_hamiltonian_from_integrals,
    get_fermion_hamiltonian,
    get_fermion_hamiltonian_from_data,
    get_fermion_hamiltonian_from_problem,
    map_fermion_hamiltonian,
    map_to_qubit_hamiltonian,
    map_prepared_problem_to_qubit,
    particle_number_basis,
    restrict_to_particle_number,
)
from .h2_pair_circuit import (
    apply_h2_pair_excitation,
    build_h2_pair_ansatz,
    prepare_hartree_fock_state,
)
from .molecule_loader import (
    H2,
    H2O,
    LiH,
    Molecule,
    get_molecular_data,
    load_molecule,
    molecule_from_string,
)
from .noise_models import (
    SYNTHETIC_NOISE_PROFILES,
    DepolarizingNoiseProfile,
    NoiseModel,
    SyntheticNoiseProfile,
    build_noisy_aer_backend,
    build_synthetic_noise_model,
    carbon_nanotube_noise,
    simple_noise_model,
)
from .pauli_measurement import (
    build_pauli_measurement_circuit,
    estimate_energy_from_paulis,
    estimate_pauli_expectation,
    evaluate_pauli_energy,
    exact_pauli_energy,
    expectation_from_counts,
    iter_pauli_terms,
    pauli_eigenvalue,
)
from .quantum_problem import PreparedQuantumProblem, prepare_quantum_problem
from .plotting import plot_comparison, plot_energy_profile, plot_vqe_convergence
from .shot_vqe_solver import ShotBasedVQESolver, evaluate_shot_vqe_objective
from .vqe_solver import (
    QiskitVQESolver,
    VQESolver,
    dense_matrix_to_sparse_pauli,
    openfermion_qubit_operator_to_sparse_pauli,
)

__version__ = "0.1.0"
__author__ = "Karim El Houdaigui"

__all__ = [
    "CAS_2_2",
    "CAS_4_4",
    "CAS_6_6",
    "CAS_8_8",
    "ALDProxyModel",
    "ActiveSpaceConfig",
    "ActiveSpaceComparisonEntry",
    "ActiveSpaceSweepConfig",
    "ActiveSpaceSweepResult",
    "AnsatzConfig",
    "AtomSpec",
    "CDR",
    "H2",
    "H2O",
    "LiH",
    "Molecule",
    "DepolarizingNoiseProfile",
    "ElectronicHamiltonianData",
    "ExperimentConfig",
    "ExperimentConfigurationError",
    "ExperimentResult",
    "GenericVQESolver",
    "MoleculeSpec",
    "NoiseModel",
    "PreparedElectronicProblem",
    "PreparedAnsatz",
    "PreparedQuantumProblem",
    "QiskitVQESolver",
    "SpinOrbitalHamiltonianData",
    "ShotBasedVQESolver",
    "StatevectorEstimatorEvaluator",
    "SyntheticNoiseProfile",
    "SYNTHETIC_NOISE_PROFILES",
    "VQESolver",
    "VQESolverConfig",
    "VQEConvergencePoint",
    "VQEResult",
    "VQERunResult",
    "ZNE",
    "avas_selection",
    "apply_h2_pair_excitation",
    "carbon_nanotube_noise",
    "define_active_space",
    "build_spin_orbital_integrals",
    "dense_matrix_to_sparse_pauli",
    "build_many_body_hamiltonian",
    "build_h2_pair_ansatz",
    "build_many_body_hamiltonian_from_data",
    "build_many_body_hamiltonian_from_integrals",
    "build_pauli_measurement_circuit",
    "build_noisy_aer_backend",
    "build_reference_state_circuit",
    "build_synthetic_noise_model",
    "get_density_matrix",
    "get_ald_proxy_model",
    "get_fermion_hamiltonian",
    "get_fermion_hamiltonian_from_data",
    "get_fermion_hamiltonian_from_problem",
    "get_fock_matrix",
    "get_molecular_data",
    "get_orbital_energies",
    "expand_to_spin_orbitals",
    "extract_electronic_hamiltonian_data",
    "estimate_energy_from_paulis",
    "estimate_pauli_expectation",
    "evaluate_pauli_energy",
    "evaluate_shot_vqe_objective",
    "exact_pauli_energy",
    "expectation_from_counts",
    "load_molecule",
    "list_ald_proxy_models",
    "map_to_qubit_hamiltonian",
    "map_fermion_hamiltonian",
    "map_prepared_problem_to_qubit",
    "iter_pauli_terms",
    "molecule_from_string",
    "openfermion_qubit_operator_to_sparse_pauli",
    "particle_number_basis",
    "pauli_eigenvalue",
    "plot_comparison",
    "plot_energy_profile",
    "plot_vqe_convergence",
    "prepare_hartree_fock_state",
    "prepare_active_space_problem",
    "prepare_ansatz",
    "prepare_quantum_problem",
    "restrict_to_particle_number",
    "run_casscf",
    "run_casci",
    "run_dft",
    "run_hartree_fock",
    "run_fci",
    "run_experiment",
    "run_vqe",
    "run_active_space_casci_reference",
    "run_active_space_sweep",
    "simple_noise_model",
    "spatial_index",
    "spin_index",
    "spin_orbital_index",
    "spin_orbital_label",
]
