"""Validation helpers for fermion-to-qubit mappings."""

from __future__ import annotations

from math import comb
from typing import Any

import numpy as np

from .classical_methods import run_fci, run_hartree_fock
from .hamiltonian_mapping import (
    build_many_body_hamiltonian,
    get_fermion_hamiltonian,
    map_to_qubit_hamiltonian_jw,
)
from .molecule_loader import H2


def _spin_orbital_integrals(mf: Any, n_spatial: int) -> tuple[np.ndarray, np.ndarray]:
    hcore_ao = mf.get_hcore()
    C = mf.mo_coeff[:, :n_spatial]
    h1_mo = C.T @ hcore_ao @ C
    eri_ao = mf.mol.intor("int2e")
    eri_mo = np.einsum("pi,qj,rk,sl,pqrs->ijkl", C, C, C, C, eri_ao, optimize=True)

    n_spin = 2 * n_spatial
    h1_spin = np.zeros((n_spin, n_spin))
    eri_spin = np.zeros((n_spin, n_spin, n_spin, n_spin))

    for p in range(n_spatial):
        for q in range(n_spatial):
            for spin in (0, 1):
                h1_spin[2 * p + spin, 2 * q + spin] = h1_mo[p, q]

    for p in range(n_spatial):
        for q in range(n_spatial):
            for r in range(n_spatial):
                for s in range(n_spatial):
                    val = eri_mo[p, r, q, s]
                    for spin_p in (0, 1):
                        for spin_q in (0, 1):
                            P = 2 * p + spin_p
                            Q = 2 * q + spin_q
                            R = 2 * r + spin_p
                            S = 2 * s + spin_q
                            eri_spin[P, Q, R, S] = val

    return h1_spin, eri_spin


def _count_ones(state: int) -> int:
    return bin(int(state)).count("1")


def _apply_annihilate(state: int, orbital: int):
    if (state >> orbital) & 1 == 0:
        return None
    mask = (1 << orbital) - 1
    sign = (-1) ** _count_ones(state & mask)
    return state & ~(1 << orbital), sign


def _apply_create(state: int, orbital: int):
    if (state >> orbital) & 1 == 1:
        return None
    mask = (1 << orbital) - 1
    sign = (-1) ** _count_ones(state & mask)
    return state | (1 << orbital), sign


def build_local_jordan_wigner_matrix(mf: Any, n_spatial: int) -> np.ndarray:
    """Build the dense JW/computational-basis matrix for small systems.

    This is a local fallback for H2-scale validation when OpenFermion is not
    installed. The occupation bitstrings are the Jordan-Wigner computational
    basis states, with fermionic signs generated by the parity strings.
    """
    h1_spin, eri_spin = _spin_orbital_integrals(mf, n_spatial)
    n_spin = 2 * n_spatial
    dim = 2**n_spin
    H = np.zeros((dim, dim))

    for ket in range(dim):
        for p in range(n_spin):
            for q in range(n_spin):
                res = _apply_annihilate(ket, q)
                if res is None:
                    continue
                state1, sign1 = res
                res = _apply_create(state1, p)
                if res is None:
                    continue
                bra, sign2 = res
                H[bra, ket] += h1_spin[p, q] * sign1 * sign2

        for p in range(n_spin):
            for q in range(n_spin):
                for r in range(n_spin):
                    for s in range(n_spin):
                        res = _apply_annihilate(ket, r)
                        if res is None:
                            continue
                        state1, sign1 = res
                        res = _apply_annihilate(state1, s)
                        if res is None:
                            continue
                        state2, sign2 = res
                        res = _apply_create(state2, q)
                        if res is None:
                            continue
                        state3, sign3 = res
                        res = _apply_create(state3, p)
                        if res is None:
                            continue
                        bra, sign4 = res
                        H[bra, ket] += (
                            0.5
                            * eri_spin[p, q, r, s]
                            * sign1
                            * sign2
                            * sign3
                            * sign4
                        )

    return H


def validate_jordan_wigner_h2(tolerance: float = 1e-4) -> dict[str, Any]:
    """Validate Jordan-Wigner mapping for H2/STO-3G in the physical sector.

    The qubit Hamiltonian acts on the full qubit Hilbert space. For a
    chemically meaningful comparison, this routine restricts the matrix to the
    occupation-number bitstrings with exactly two electrons, then compares the
    ground-state energy in that block to PySCF FCI. Energies returned with
    ``*_electronic`` exclude nuclear repulsion; energies returned with
    ``*_total`` include it. OpenFermion is used when available; otherwise a
    local dense Jordan-Wigner matrix is built for this H2-scale validation.
    """
    molecule = H2()
    mf, _hf_total = run_hartree_fock(molecule)
    _fci_solver, fci_total = run_fci(molecule, mf)
    nuclear_repulsion = float(mf.mol.energy_nuc())
    fci_electronic = float(fci_total - nuclear_repulsion)

    active_space = {"num_electrons": 2, "num_spatial_orbitals": mf.mo_coeff.shape[1]}
    local_hamiltonian, basis = build_many_body_hamiltonian(mf, active_space)
    local_ground_electronic = float(np.min(np.linalg.eigvalsh(local_hamiltonian)))

    n_spin_orbitals = 2 * active_space["num_spatial_orbitals"]
    mapping_backend = "local_dense_jordan_wigner"
    try:
        import openfermion  # type: ignore[import-not-found]

        fermion_hamiltonian = get_fermion_hamiltonian(mf, active_space)
        qubit_hamiltonian = map_to_qubit_hamiltonian_jw(fermion_hamiltonian)
        get_sparse_operator = getattr(openfermion, "get_sparse_operator", None)
        if get_sparse_operator is None:
            get_sparse_operator = getattr(openfermion.utils, "get_sparse_operator", None)
        if get_sparse_operator is None:
            raise AttributeError("OpenFermion get_sparse_operator is unavailable")
        sparse_qubit = get_sparse_operator(qubit_hamiltonian, n_qubits=n_spin_orbitals)
        full_qubit_matrix = sparse_qubit.toarray()
        mapping_backend = "openfermion_jordan_wigner"
    except (ImportError, AttributeError):
        full_qubit_matrix = build_local_jordan_wigner_matrix(
            mf,
            active_space["num_spatial_orbitals"],
        )

    rows = np.asarray(basis, dtype=int)
    fixed_particle_block = full_qubit_matrix[rows[:, None], rows]
    jw_ground_electronic = float(np.min(np.linalg.eigvalsh(fixed_particle_block)))
    jw_total = jw_ground_electronic + nuclear_repulsion
    gap_total = jw_total - fci_total

    return {
        "molecule": molecule.name,
        "basis": molecule.mol.basis,
        "n_spin_orbitals": int(n_spin_orbitals),
        "n_qubits": int(n_spin_orbitals),
        "n_electrons": active_space["num_electrons"],
        "fixed_particle_sector_dimension": comb(
            n_spin_orbitals,
            active_space["num_electrons"],
        ),
        "mapping_backend": mapping_backend,
        "nuclear_repulsion_hartree": nuclear_repulsion,
        "fci_electronic_hartree": fci_electronic,
        "fci_total_hartree": float(fci_total),
        "local_ground_electronic_hartree": local_ground_electronic,
        "jw_qubit_ground_electronic_hartree": jw_ground_electronic,
        "jw_qubit_ground_total_hartree": jw_total,
        "jw_total_minus_fci_total_hartree": gap_total,
        "tolerance_hartree": tolerance,
        "status": "PASS" if abs(gap_total) < tolerance else "FAIL",
    }
