"""Validation helpers for fermion-to-qubit mappings."""

from __future__ import annotations

from math import comb
from typing import Any

import numpy as np

from .classical_methods import run_fci, run_hartree_fock
from .electronic_structure import (
    ElectronicHamiltonianData,
    expand_to_spin_orbitals,
    extract_electronic_hamiltonian_data,
)
from .hamiltonian_mapping import (
    build_many_body_hamiltonian_from_data,
    get_fermion_hamiltonian_from_data,
    map_to_qubit_hamiltonian_jw,
)
from .molecule_loader import H2
from .validation.jordan_wigner_reference import (
    decompose_pauli,
    number_operator_from_z,
    reference_jw_hamiltonian,
    reference_number_operator,
)
from .vqe_solver import openfermion_qubit_operator_to_sparse_pauli


def _spin_orbital_integrals(mf: Any, n_spatial: int) -> tuple[np.ndarray, np.ndarray]:
    data = extract_electronic_hamiltonian_data(mf, orbital_indices=range(n_spatial))
    spin_data = expand_to_spin_orbitals(data)
    return spin_data.h1, spin_data.eri


def _count_ones(state: int) -> int:
    return bin(int(state)).count("1")


def _apply_annihilate(state: int, orbital: int):
    if (state >> orbital) & 1 == 0:
        return None
    mask = (1 << orbital) - 1
    sign = (-1) ** _count_ones(state & mask)
    return state & ~(1 << orbital), sign


def _apply_create(state: int, orbital: int):
    if (state >> orbital) & 1 == 1:
        return None
    mask = (1 << orbital) - 1
    sign = (-1) ** _count_ones(state & mask)
    return state | (1 << orbital), sign


def build_local_jordan_wigner_matrix(mf: Any, n_spatial: int) -> np.ndarray:
    """Build the dense JW/computational-basis matrix for small systems.

    This is a local fallback for H2-scale validation when OpenFermion is not
    installed. The occupation bitstrings are the Jordan-Wigner computational
    basis states, with fermionic signs generated by the parity strings.
    """
    data = extract_electronic_hamiltonian_data(mf, orbital_indices=range(n_spatial))
    return build_local_jordan_wigner_matrix_from_data(data)


def build_local_jordan_wigner_matrix_from_data(data: ElectronicHamiltonianData) -> np.ndarray:
    """Build the dense full-Fock-space matrix from canonical electronic data."""
    spin_data = expand_to_spin_orbitals(data)
    h1_spin, eri_spin = spin_data.h1, spin_data.eri
    n_spin = data.n_spin_orbitals
    dim = 2**n_spin
    H = np.zeros((dim, dim))

    for ket in range(dim):
        for p in range(n_spin):
            for q in range(n_spin):
                res = _apply_annihilate(ket, q)
                if res is None:
                    continue
                state1, sign1 = res
                res = _apply_create(state1, p)
                if res is None:
                    continue
                bra, sign2 = res
                H[bra, ket] += h1_spin[p, q] * sign1 * sign2

        for p in range(n_spin):
            for q in range(n_spin):
                for r in range(n_spin):
                    for s in range(n_spin):
                        res = _apply_annihilate(ket, r)
                        if res is None:
                            continue
                        state1, sign1 = res
                        res = _apply_annihilate(state1, s)
                        if res is None:
                            continue
                        state2, sign2 = res
                        res = _apply_create(state2, q)
                        if res is None:
                            continue
                        state3, sign3 = res
                        res = _apply_create(state3, p)
                        if res is None:
                            continue
                        bra, sign4 = res
                        H[bra, ket] += (
                            0.5
                            * eri_spin[p, q, r, s]
                            * sign1
                            * sign2
                            * sign3
                            * sign4
                        )

    return H


def _bit_reversal_permutation(n_qubits: int) -> np.ndarray:
    """Map project/Qiskit basis indices to OpenFermion sparse-matrix indices."""
    return np.asarray(
        [int(f"{index:0{n_qubits}b}"[::-1], 2) for index in range(2**n_qubits)],
        dtype=int,
    )


def _openfermion_pauli_coefficients(qubit_operator: Any, n_qubits: int) -> dict[str, complex]:
    """Return OpenFermion terms as Qiskit-style big-endian labels."""
    coefficients: dict[str, complex] = {}
    for term, coefficient in qubit_operator.terms.items():
        label = ["I"] * n_qubits
        for qubit, pauli in term:
            label[n_qubits - 1 - qubit] = pauli
        coefficients["".join(label)] = complex(coefficient)
    return coefficients


def validate_jordan_wigner_h2(tolerance: float = 1e-4) -> dict[str, Any]:
    """Validate Jordan-Wigner mapping for H2/STO-3G in the physical sector.

    The qubit Hamiltonian acts on the full qubit Hilbert space. For a
    chemically meaningful comparison, this routine restricts the matrix to the
    occupation-number bitstrings with exactly two electrons, then compares the
    ground-state energy in that block to PySCF FCI. Energies returned with
    ``*_electronic`` exclude nuclear repulsion; energies returned with
    ``*_total`` include it. OpenFermion is used when available; otherwise a
    local dense Jordan-Wigner matrix is built for this H2-scale validation.
    """
    molecule = H2()
    mf, _hf_total = run_hartree_fock(molecule)
    _fci_solver, fci_total = run_fci(molecule, mf)
    data = extract_electronic_hamiltonian_data(mf)
    nuclear_repulsion = data.nuclear_repulsion
    fci_electronic = float(fci_total - nuclear_repulsion)

    active_space = {"num_electrons": data.n_electrons, "num_spatial_orbitals": data.n_spatial_orbitals}
    local_hamiltonian, basis = build_many_body_hamiltonian_from_data(data)
    local_ground_electronic = float(np.min(np.linalg.eigvalsh(local_hamiltonian)))

    import openfermion  # type: ignore[import-not-found]

    n_spin_orbitals = data.n_spin_orbitals
    spin_data = expand_to_spin_orbitals(data)
    reference_matrix = reference_jw_hamiltonian(spin_data)
    fermion_hamiltonian = get_fermion_hamiltonian_from_data(data)
    qubit_hamiltonian = map_to_qubit_hamiltonian_jw(fermion_hamiltonian)
    raw_openfermion_matrix = openfermion.get_sparse_operator(
        qubit_hamiltonian,
        n_qubits=n_spin_orbitals,
    ).toarray()
    permutation = _bit_reversal_permutation(n_spin_orbitals)
    openfermion_matrix = raw_openfermion_matrix[np.ix_(permutation, permutation)]
    sparse_pauli = openfermion_qubit_operator_to_sparse_pauli(
        qubit_hamiltonian,
        n_spin_orbitals,
    )
    qiskit_matrix = np.asarray(sparse_pauli.to_matrix(), dtype=complex)

    reference_vs_openfermion = float(np.linalg.norm(reference_matrix - openfermion_matrix))
    openfermion_vs_qiskit = float(np.linalg.norm(openfermion_matrix - qiskit_matrix))
    reference_pauli = decompose_pauli(reference_matrix)
    openfermion_pauli = _openfermion_pauli_coefficients(qubit_hamiltonian, n_spin_orbitals)
    all_labels = set(reference_pauli) | set(openfermion_pauli)
    pauli_coefficient_error = float(
        max(abs(reference_pauli.get(label, 0.0) - openfermion_pauli.get(label, 0.0)) for label in all_labels)
    )

    hermiticity_errors = {
        "reference": float(np.linalg.norm(reference_matrix - reference_matrix.conj().T)),
        "openfermion": float(np.linalg.norm(openfermion_matrix - openfermion_matrix.conj().T)),
        "qiskit": float(np.linalg.norm(qiskit_matrix - qiskit_matrix.conj().T)),
    }
    hermiticity_error = max(hermiticity_errors.values())

    number_operator = reference_number_operator(n_spin_orbitals)
    number_from_z = number_operator_from_z(n_spin_orbitals)
    number_operator_error = float(np.linalg.norm(number_operator - number_from_z))
    commutator_norm = float(
        np.linalg.norm(reference_matrix @ number_operator - number_operator @ reference_matrix)
    )

    sectors = {
        particle_number: [
            state
            for state in range(2**n_spin_orbitals)
            if _count_ones(state) == particle_number
        ]
        for particle_number in range(n_spin_orbitals + 1)
    }
    sector_dimensions = {str(number): len(states) for number, states in sectors.items()}
    max_cross_sector_norm = 0.0
    for left_number, left_states in sectors.items():
        for right_number, right_states in sectors.items():
            if left_number == right_number:
                continue
            block = reference_matrix[np.ix_(left_states, right_states)]
            max_cross_sector_norm = max(max_cross_sector_norm, float(np.linalg.norm(block)))

    fixed_basis_index = {occupation: index for index, occupation in enumerate(basis)}
    aligned_states = sorted(sectors[data.n_electrons], key=fixed_basis_index.__getitem__)
    fixed_particle_block = reference_matrix[np.ix_(aligned_states, aligned_states)]
    fixed_n_matrix_error = float(np.linalg.norm(fixed_particle_block - local_hamiltonian))
    fixed_spectrum = np.linalg.eigvalsh(local_hamiltonian)
    jw_spectrum = np.linalg.eigvalsh(fixed_particle_block)
    fixed_n_spectrum_error = float(np.max(np.abs(jw_spectrum - fixed_spectrum)))

    jw_ground_electronic = float(np.min(np.linalg.eigvalsh(fixed_particle_block)))
    jw_total = jw_ground_electronic + nuclear_repulsion
    gap_total = jw_total - fci_total
    hf_state = (1 << 0) | (1 << 1)
    hf_vector = np.zeros(2**n_spin_orbitals, dtype=complex)
    hf_vector[hf_state] = 1.0
    hf_particle_number = float(np.real(hf_vector.conj() @ number_operator @ hf_vector))
    hf_electronic = float(np.real(hf_vector.conj() @ reference_matrix @ hf_vector))
    hf_total_from_jw = hf_electronic + nuclear_repulsion
    hf_total_error = float(hf_total_from_jw - _hf_total)
    fci_electronic_error = float(jw_ground_electronic - fci_electronic)

    strict_tolerance = 1e-10
    checks = [
        reference_vs_openfermion < strict_tolerance,
        openfermion_vs_qiskit < strict_tolerance,
        pauli_coefficient_error < strict_tolerance,
        hermiticity_error < strict_tolerance,
        number_operator_error < strict_tolerance,
        commutator_norm < strict_tolerance,
        max_cross_sector_norm < strict_tolerance,
        fixed_n_matrix_error < strict_tolerance,
        fixed_n_spectrum_error < strict_tolerance,
        abs(hf_particle_number - data.n_electrons) < strict_tolerance,
        abs(hf_total_error) < strict_tolerance,
        abs(fci_electronic_error) < tolerance,
        abs(gap_total) < tolerance,
    ]

    return {
        "molecule": molecule.name,
        "basis": molecule.mol.basis,
        "n_spin_orbitals": int(n_spin_orbitals),
        "n_qubits": int(n_spin_orbitals),
        "n_electrons": active_space["num_electrons"],
        "fixed_particle_sector_dimension": comb(
            n_spin_orbitals,
            active_space["num_electrons"],
        ),
        "mapping_backend": "openfermion_jordan_wigner",
        "num_fermionic_terms": len(fermion_hamiltonian.terms),
        "num_pauli_terms": len(qubit_hamiltonian.terms),
        "num_reference_pauli_terms": len(reference_pauli),
        "reference_vs_openfermion_matrix_error": reference_vs_openfermion,
        "openfermion_vs_qiskit_matrix_error": openfermion_vs_qiskit,
        "pauli_coefficient_error": pauli_coefficient_error,
        "hermiticity_error": hermiticity_error,
        "hermiticity_errors": hermiticity_errors,
        "particle_number_operator_error": number_operator_error,
        "particle_number_commutator_norm": commutator_norm,
        "sector_dimensions": sector_dimensions,
        "max_cross_sector_block_norm": max_cross_sector_norm,
        "fixed_n_matrix_error": fixed_n_matrix_error,
        "fixed_n_spectrum_error": fixed_n_spectrum_error,
        "hf_basis_state": hf_state,
        "hf_particle_number": hf_particle_number,
        "hf_electronic_hartree": hf_electronic,
        "hf_total_hartree": hf_total_from_jw,
        "hf_total_error_hartree": hf_total_error,
        "nuclear_repulsion_hartree": nuclear_repulsion,
        "fci_electronic_hartree": fci_electronic,
        "fci_total_hartree": float(fci_total),
        "local_ground_electronic_hartree": local_ground_electronic,
        "jw_qubit_ground_electronic_hartree": jw_ground_electronic,
        "jw_qubit_ground_total_hartree": jw_total,
        "jw_total_minus_fci_total_hartree": gap_total,
        "jw_electronic_minus_fci_electronic_hartree": fci_electronic_error,
        "tolerance_hartree": tolerance,
        "matrix_tolerance": strict_tolerance,
        "status": "PASS" if all(checks) else "FAIL",
    }
